name: Build Meticulo App

on: workflow_dispatch

env:
  FILENAME: Meticulo V${{vars.VERSION}}
  BUILD_DIR: .android

jobs:
  build_for_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
          run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --release
      - name: Archive APK
        run: mkdir -p ${{env.BUILD_DIR}} && mv build/app/outputs/flutter-apk/app-release.apk ${{env.BUILD_DIR}}/${{env.FILENAME}}.apk
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.FILENAME}}
          path: ${{env.BUILD_DIR}}